apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osrm-server-car.name" . }}
  labels:
{{ include "osrm-server-car.labels.standard" . | indent 4 }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ include "osrm-server-car.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "osrm-server-car.name" . }}
        release: {{ .Release.Name }}
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.hub }}/osrm-server-car:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['sh', '-c', 'fetcher && osrm-routed --algorithm mld --max-table-size 10000 /osrm-data/map.osrm']
        ports:
        {{- range $key, $val := .Values.service.ports }}
        - containerPort: {{ $val.port }}
        {{- end }}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/serviceaccount.json"
        - name: OSRM_BUILDER_VERSION
          value: {{ .Values.osrm.builder.version }}
        volumeMounts:
        - name: google-service-account
          readOnly: true
          mountPath: "/etc/secrets"
        - name: osrm-data
          mountPath: "/osrm-data"
{{- if .Values.probes.enabled }}
        readinessProbe:
          httpGet:
            path: "/route/v1/driving/-99.170449,19.426162;-99.170075,19.426347"
            port: 5000
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
{{- end }}
      volumes:
      - name: google-service-account
        secret:
          secretName: google-storage-viewer
      - name: osrm-data
        emptyDir: {}
