apiVersion: v1
kind: Service
metadata:
  name: {{ include "osrm-server-car.name" .}}
  labels:
{{ include "osrm-server-car.labels.standard" . | indent 4 }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    name: {{ .Values.service.name }}
  selector:
    app: {{ include "osrm-server-car.name" . }}
    release: {{ .Release.Name }}
